POST http://127.0.0.1/consentimientos/php/generacons_aclaramiento.php HTTP/1.1
content-type: application/json

{
    "identificacion": "9695141",
    "nombre": "CESAR LEANDRO PATIÑO VELEZ",
    "representado":"YENIFER IDARRAGA",
    "$dia":"20",
    "mes":"septiembre",
    "anio":"2024",
    "firma":"ñdfksñldfksñldfksñdlfkñ"
}